### ISSUE TITLE
for c programs the ouput is not printing on the console as it should be 

### ISSUE THREAD

**Issue by Indratejreddy** [rkstrdee/night-hacker-dark-theme#3] opened 2021-09-07 16:27 UTC
```
#include <stdio.h>
void main(){
    char lc=-1;
    printf("%c",lc);
}
```

output should be : � hi

but on console it is not visible on this theme  
the output is :
![image](https://user-images.githubusercontent.com/66834653/132379474-ff452be9-def7-492b-95f2-fd5802f97080.png)

**Comment by ddh4r4m** [comment] 2021-09-07 16:45
I'm not able to reproduce the error, can you share the code which you are trying to run ?
I ran the code you provided, but it is displayed perfectly.
![image](https://user-images.githubusercontent.com/42842402/132381895-a4e90d7e-3b44-4444-bd81-59020d2c112e.png)

**Comment by Indratejreddy** [comment] 2021-09-07 16:55
for me it is not printing the question mark
![image](https://user-images.githubusercontent.com/66834653/132382954-3e2da34a-94e5-4304-9bc1-f9a13a69a652.png)

**Comment by ddh4r4m** [comment] 2021-09-07 17:16
This might be an issue with the font you are using, Try switching to something else / coding fonts for terminal. And you can close this issue if it gets resolved.

**Comment by Indratejreddy** [comment] 2021-09-08 00:49
no, it is not the issue my terminal font is default font

**Comment by ddh4r4m** [comment] 2021-09-08 05:24
Do you see the output in other themes ? can you post that screenshot ?

**Closed as completed** 2021-09-20 20:10 UTC
